### ISSUE TITLE
Travis build failing in master

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-docker#158]
https://travis-ci.com/github/pulumi/pulumi-docker

```

[ /pulumi-docker/examples/aws-py ]       File "/home/travis/gopath/src/github.com/pulumi/pulumi-docker/sdk/python/bin/pulumi_docker/docker.py", line 421, in build_image_async
1726[ /pulumi-docker/examples/aws-py ]         f'No digest available for image {image_name}', log_resource)
1727[ /pulumi-docker/examples/aws-py ]     pulumi_docker.docker.ResourceError: No digest available for image 894850187425.dkr.ecr.us-west-2.amazonaws.com/my-repo-e720121
1728[ /pulumi-docker/examples/aws-py ]     error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

**Comment by lukehoban** [comment]
@rienafairefr We are seeing transient (but fairly common) failures of the two Python tests in this repository after merging in #155 and #156.

From the errors I'm seeing, it looks like the `docker image inspect` is actually running before the `docker build` completes.  I have a feeling there is an issue with the threading code in `run_command_that_can_fail`, but have not had time yet to fully audit it.  I also unfortunately cannot reproduce the issue locally.  

If you have a chance to take a look - would love any help on this.  🙌

**Comment by rienafairefr** [comment]
I can confirm the issue. I add intermittent failures as well, locally or not, and I also suspected a race condition between the `build` and the `inspect`. I had added a caveat to #141 that I suspected the async code wasn't up to par, I was apparently right :+1:

I suspect that the async code fails in `run_command_that_can_fail` because I used `subprocess` to run the `docker` commands. There is a `Popen.communicate` in `run_command_that_can_fail` that should make it wait the end of the process, but maybe it waits in a way that is incompatible with async code. I'll investigate, maybe use something more async-y to run the docker commands
