### ISSUE TITLE
Support multi-arch images (aka v2 or OCI Image Index manifests)

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-docker#296]
Docker for Mac requires using `buildx` for building docker images that are cross platform.

There are also other scenarios that would require use of build.

Currently, this provider doesn't support them, we should add support

**Comment by mattstratton** [comment]
See also https://github.com/pulumi/pulumi/discussions/7428 for more context

**Comment by mattstratton** [comment]
additional resource https://docs.docker.com/buildx/working-with-buildx/

**Comment by aterreno** [comment]
So from my understanding (the thought process is all in the discussion linked above) 

when you spawn a docker build, you will run docker and the 'aliasing' to buildx is not there. 

The simplest solution that can I can think of right now is either a flag to say 'runAsBuildx' or have a specific interface when  wanting to run a `docker build` as a `docker buildx build`. 

Pasting here some code I got to work while debugging the issue

```
const { spawn } = require("child_process");

const command = {
    cmd: 'docker',
    args: [
      'buildx',
      'build',
      '--platform',
      'linux/amd64,linux/arm64,linux/arm/v7',
      '.',
    ]
  }

const p = spawn(command.cmd, command.args, process.env);

p.stdout.on("data", (data) => {
  console.log(`stdout: ${data}`);
});

p.stderr.on("data", (data) => {
  console.error(`stderr: ${data}`);
});

p.on("close", (code) => {
  console.log(`child process exited with code ${code}`);
});
``` 

The only workaround I can think of, for my use, is to stop building images in pulumi, so pre-bake them before a pulumi up and then referencing them... 

It's that or get a Linux laptop really 😭

**Comment by willieseabrook** [comment]
This seems pretty important to me. I work across osx and linux.

**Comment by multirise** [comment]
this is an issue that can only get worse with Mac users, it's only a matter of time.

**Comment by tim-hoffmann** [comment]
Any news here? I think this is urgent for Mac M1 users.

**Comment by benesch** [comment]
Shameless plug: we built a new Docker provider at @MaterializeInc that uses Buildkit directly. It's been working great for us on M1 macs and supports cross-platform builds: https://github.com/MaterializeInc/pulumi-docker-buildkit

**Comment by jkodroff** [comment]
Note that using environment variables as a workaround won't work in Python until this issue is resolved: https://github.com/pulumi/pulumi-docker/pull/311

**Comment by jdmaguire** [comment]
Another use case for BuildX is multiple build contexts.

**Comment by guineveresaenger** [comment]
Hi Everyone - we're working on a version 4.0 that supports Buildkit as default.
Still very much in alpha but being actively worked on.

**Comment by guineveresaenger** [comment]
Unfortunately, I do not believe this has been properly addressed by #471. Will have to reopen.

**Comment by AaronFriel** [comment]
Thanks everyone for you interest in this issue! We're looking to address this along with many other issues (such as #132) in the next major release with a number of new features and bug fixes. 

In the next release we no longer rely on shelling out to the Docker CLI, instead using the high level `docker/docker/client` SDK. That improves the ergonomics and will allow us to close a number of issues, but it also means we can't close this issue as the title is written. We won't support running `docker buildx` because we aren't running `docker` the CLI. We're also tracking an upstream issue to identify if we can make `Image` build and push a multi-arch image with a single resource:
- https://github.com/docker/roadmap/issues/371

Per the above, I'm rewriting this issue title as "Support multi-arch images".

We should be able to close #471, "Enable cross platform builds". That addresses the main request here: build an image for a platform other than the one the user is using. This may also be possible today by setting `extraOptions: ["--platform", "linux/amd64"]` with newer CLIs.

We'll also investigate providing a workaround to create and push multi-arch images, and we'll have more on that closer to the release of the next major version.

**Comment by jkodroff** [comment]
The best workaround to create a multi-arch image (that I can think of, anyway) follows:

1. Create a `docker.Image` to build a single-arch image for e.g. `arm64`.
2. Create another `docker.Image` to build a single-arch image for e.g. `amd64`.
3. Create a `pulumi.Command.local` (Pulumi Command provider) to run `docker manifest` to create the multi-arch image.

We use a similar approach in building Pulumi's Docker images here: https://github.com/pulumi/pulumi-docker-containers/blob/main/.github/workflows/release.yml#L198-L204

**Comment by blampe** [comment]
Hi folks, we just released a new Docker Build provider focused exclusively on building images with buildx/BuildKit. It provides support for multi-platform images out of the box, and we recommend you use it for building images going forward. Please take a look and give us feedback!

The repository is [here](https://github.com/pulumi/pulumi-docker-build); our blog announcement is [here](https://www.pulumi.com/blog/docker-build/); and finally API docs are [here](https://www.pulumi.com/registry/packages/docker-build/) along with examples of how to migrate your existing `Image` resources to `dockerbuild.Image`.

We won't be able to add this functionality in this provider for a number of reasons, so I'm closing this as wont-fix.
