### ISSUE TITLE
Repeated image tags when providing a tag explicitly

### ISSUE THREAD

**Issue by mazamats** [pulumi/pulumi-docker#41]
Running into an issue after the latest `v0.16.1` update.

When building a docker image with a custom tag,  the tag is appended twice causing the build to fail.

Example:

```javascript
const image = new docker.Image("name", {
  imageName: "XXXXXXXX:1.10.0",
  build: {
    context: "docker/standardBuild"
  },
}, {});
```

Results in:

```shell
Error: 'docker tag ............' failed with exit code 1

    at /root/project/node_modules/@pulumi/docker.ts:514:15
    at Generator.next (<anonymous>)
    at fulfilled (/root/project/node_modules/@pulumi/docker/docker.js:17:58)

Error parsing reference: "XXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/YYYYYYYYYY:1.10.0:1.10.0-aab6ab353994549bf09036f98f579ef871ab06545f4b6f9a78b69a9b99da8068" is not a valid repository/tag: invalid reference format

```

**Comment by lukehoban** [comment]
https://github.com/pulumi/pulumi-docker/pull/42 is open to address this.

**Comment by CyrusNajmabadi** [comment]
Actually, looking more into this, i think the correct fix is to do:

```ts
const image = new docker.Image("name", {
  localImageName: "XXXXXXXX:1.10.0"
  imageName: "XXXXXXXX",
  build: {
    context: "docker/standardBuild"
  },
}, {});
```

Basically, all the fix does is strip off the tag from imageName if it is provided.  It never uses that tag for anything though.  So, in effect, it is saying "imageName should not have a tag".  The above snippet accomplishes the same.

I think the potentially better fix would be to check for this and have the docker code throw if a tag is provided on imageName since it's not used and will only cause problems.

**Comment by CyrusNajmabadi** [comment]
Ignore the above.  It will work.  But i think we should just support imageName containing a tag.
