### ISSUE TITLE
Document that images aren't deleted on `destroy`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-docker#588]
I noticed today after deploying into a locally running Docker environment and then running `pulumi destroy` that the images created by `docker.Image` weren't deleted. This surprised me a bit (I was expecting them to be removed), so I [asked about it internally](https://pulumi.slack.com/archives/C04A7AKMGP4/p1681752930844759), and it sounds like it was an intentional design choice aimed at preventing potential outages. We should document this behavior so users know how it works and why.

**Comment by scottslowe** [comment]
Per @guineveresaenger, although images created by `docker.Image` aren't deleted on `pulumi destroy`, images created with docker.RemoteImage` _are_ deleted. Whatever documentation updates we do should include this distinction so that users have a clear understanding of which images will or will not be removed on a `pulumi destroy` operation.

**Comment by guineveresaenger** [comment]
Thank you for filing this issue!
