### ISSUE TITLE
VSCode crashing building containers

### ISSUE THREAD

**Issue by martinjt** [pulumi/pulumi-docker#875]
### What happened?

VSCode crashes whenever I try to build a docker image inside of a Devcontainer

The error message `error listing credentials` is displayed.

I've tried 2 separate machines. Also the repo works fine on pure WSL2, so it's something to do with devcontainers specifically.

### Example

* Clone this repo: https://github.com/martinjt/pulumi-aws-custom-collector
* Open in the devcontainer
* run pulumi up.
* vscode will crash without building the image with an error

### Output of `pulumi about`

CLI          
Version      3.96.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.13.1
awsx    2.3.0
docker  4.5.0
docker  3.6.1
nodejs  unknown

Host     
OS       debian
Version  11.8
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.10.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/martinjt
User           martinjt
Organizations  ***, ***
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.95.0
@types/node     16.18.68
@pulumi/aws     6.13.1
@pulumi/awsx    2.3.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Additional context

This is specifically on Windows using WSL2 and Docker Desktop, I haven't been able to try it on Mac or other architectures.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
I was not able to reproduce this on my machine; the image built successfully, but did not upload (because the `registryInfo` is commented out I believe). 

I suspect the crash you are seeing could be caused by exhausting the memory in the container. You might try cranking the settings up in your VM host and see if that helps. 

Another bit of debugging to try could be to try running `docker build` directly inside your container.
